use_frameworks!

platform :ios, '9.0'

target 'CommonLib_Example' do
  pod 'CommonLib', :path => '../'
  pod 'RxSwift', '~> 4.0'
  pod 'RxCocoa', '~> 4.0'

  target 'CommonLib_Tests' do
    inherit! :search_paths

    
  end
end
